import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb68b',
        'on-tertiary-fixed': '#321200',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#ff9249',
        'tertiary-container': '#6d3000',
        'on-background': '#1a1c1d',
        'tertiary': '#4b1f00',
        'surface-variant': '#e2e2e3',
        'surface': '#f9f9fa',
        'on-error': '#ffffff',
        'surface-tint': '#2b695a',
        'surface-container-high': '#e8e8e9',
        'primary-container': '#004b3e',
        'primary': '#003229',
        'on-secondary-fixed-variant': '#364e00',
        'outline-variant': '#bfc9c4',
        'surface-container-highest': '#e2e2e3',
        'on-surface': '#1a1c1d',
        'background': '#f9f9fa',
        'secondary-fixed': '#c5f273',
        'on-primary-fixed': '#00201a',
        'surface-container-low': '#f3f3f4',
        'on-secondary': '#ffffff',
        'secondary': '#486800',
        'inverse-primary': '#95d3c1',
        'inverse-surface': '#2f3132',
        'primary-fixed': '#b0efdd',
        'surface-container': '#eeeeef',
        'surface-dim': '#dadadb',
        'primary-fixed-dim': '#95d3c1',
        'on-primary-fixed-variant': '#0a5043',
        'tertiary-fixed': '#ffdbc8',
        'secondary-fixed-dim': '#a9d55a',
        'outline': '#707975',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'on-secondary-container': '#4d6e00',
        'error': '#ba1a1a',
        'on-primary-container': '#7dbaa9',
        'on-surface-variant': '#404945',
        'surface-bright': '#f9f9fa',
        'inverse-on-surface': '#f1f1f1',
        'secondary-container': '#c5f273',
        'on-secondary-fixed': '#131f00',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#753400',
      },
      borderRadius: {
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        'stack-sm': '8px',
        'stack-lg': '48px',
        'gutter': '32px',
        'section-padding': '120px',
        'container-max': '1280px',
        'stack-md': '24px',
      },
      fontFamily: {
        'headline-xl': ['Manrope'],
        'body-md': ['Work Sans'],
        'label-caps': ['Work Sans'],
        'headline-lg': ['Manrope'],
        'body-lg': ['Work Sans'],
        'headline-md': ['Manrope'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config;